version: '3.3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ../Data/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=changeme # CHANGEME
      - MYSQL_ROOT_PASSWORD=changeme # CHANGEME
      - MYSQL_DATABASE=changeme # CHANGEME
    labels:
      - "database"
